/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mvc.View;

import controller.AdminController;
import controller.WorkerController.Worker;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Legion
 */
public class ManageWorker extends javax.swing.JPanel {

    /**
     * Creates new form ManageWorker
     */
    public ManageWorker() {
        initComponents();
initializeWorkerTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_input = new swing.TextField();
        phone_input = new swing.TextField();
        email_input = new swing.TextField();
        id_btn = new swing.Button();
        phone_btn = new swing.Button();
        email_btn = new swing.Button();
        clear_btn = new swing.Button();
        filter_btn = new swing.Button();
        delete_btn = new swing.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        worker_table = new javax.swing.JTable();
        worker_id = new javax.swing.JTextField();

        setBackground(new java.awt.Color(4, 44, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Phone:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Email:");

        id_input.setText("");
        id_input.setPlaceholder("");

        phone_input.setPlaceholder("");

        email_input.setPlaceholder("");

        id_btn.setBackground(new java.awt.Color(4, 44, 90));
        id_btn.setForeground(new java.awt.Color(255, 255, 255));
        id_btn.setText("SEARCH");
        id_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_btnActionPerformed(evt);
            }
        });

        phone_btn.setBackground(new java.awt.Color(4, 44, 90));
        phone_btn.setForeground(new java.awt.Color(255, 255, 255));
        phone_btn.setText("SEARCH");
        phone_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_btnActionPerformed(evt);
            }
        });

        email_btn.setBackground(new java.awt.Color(4, 44, 90));
        email_btn.setForeground(new java.awt.Color(255, 255, 255));
        email_btn.setText("SEARCH");
        email_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_btnActionPerformed(evt);
            }
        });

        clear_btn.setBackground(new java.awt.Color(4, 44, 90));
        clear_btn.setForeground(new java.awt.Color(255, 255, 255));
        clear_btn.setText("CLEAR");
        clear_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        filter_btn.setBackground(new java.awt.Color(4, 44, 90));
        filter_btn.setForeground(new java.awt.Color(255, 255, 255));
        filter_btn.setText("FILTER");
        filter_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_input, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                            .addComponent(phone_input, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                            .addComponent(email_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                        .addComponent(filter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        delete_btn.setBackground(new java.awt.Color(204, 204, 204));
        delete_btn.setForeground(new java.awt.Color(255, 51, 51));
        delete_btn.setText("DELETE");
        delete_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_btnMouseClicked(evt);
            }
        });
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        worker_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Email", "Working Sector", "Gender", "Phone", "Password"
            }
        ));
        jScrollPane1.setViewportView(worker_table);

        worker_id.setText("worker_id");
        worker_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worker_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(worker_id, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(worker_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void id_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_btnActionPerformed

    private void phone_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_btnActionPerformed

    private void email_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_btnActionPerformed

    private void filter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filter_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_btnActionPerformed

    private void worker_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worker_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_worker_idActionPerformed

    private void delete_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_btnMouseClicked
        // TODO add your handling code here:
		int workerId = Integer.parseInt(worker_id.getText());
		boolean success = AdminController.deleteWorker(workerId);
		if(success){
			JOptionPane.showMessageDialog(this, "removed!!", "Information", JOptionPane.INFORMATION_MESSAGE);
initializeWorkerTable();
		}else {
			JOptionPane.showMessageDialog(this, "failed", "Error", JOptionPane.INFORMATION_MESSAGE);
		}
    }//GEN-LAST:event_delete_btnMouseClicked

	public void initializeWorkerTable() {
		// Set table formatting
		worker_table.setRowMargin(10);
		worker_table.setIntercellSpacing(new Dimension(15, 10));
		worker_table.setRowHeight(30);

		// Create and set table model
		DefaultTableModel model = new DefaultTableModel(
				new Object[][]{},
				new String[]{"ID", "First Name", "Last Name", "Email", "Category", "Phone", "Gender"}
		) {
			@Override
			public boolean isCellEditable(int row, int column) {
				return false; // Make table read-only
			}
		};
		worker_table.setModel(model);

		// Load all workers initially
		displayAllWorkers();

		// Add button listeners
		filter_btn.addActionListener(e -> filterWorkers());
		clear_btn.addActionListener(e -> {
			clearInputs();
			displayAllWorkers();
		});
	}

	private void filterWorkers() {
		String id = id_input.getText().trim();
		String phone = phone_input.getText().trim();
		String email = email_input.getText().trim();

		Worker worker = null;

		if (!id.isEmpty()) {
			try {
				worker = AdminController.getWorkerById(Integer.parseInt(id));
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(this, "Please enter a valid ID", "Error", JOptionPane.ERROR_MESSAGE);
				return;
			}
		} else if (!phone.isEmpty()) {
			worker = AdminController.getWorkerByPhone(phone);
		} else if (!email.isEmpty()) {
			worker = AdminController.getWorkerByEmail(email);
		}

		DefaultTableModel model = (DefaultTableModel) worker_table.getModel();
		model.setRowCount(0);

		if (worker != null) {
			model.addRow(new Object[]{
				worker.getWorkerId(),
				worker.getFirstName(),
				worker.getLastName(),
				worker.getEmail(),
				worker.getCategory(),
				worker.getPhone(),
				worker.getGender()
			});
		} else {
			JOptionPane.showMessageDialog(this, "No worker found", "Information", JOptionPane.INFORMATION_MESSAGE);
		}
	}

	private void clearInputs() {
		id_input.setText("");
		phone_input.setText("");
		email_input.setText("");
	}

	private void displayAllWorkers() {
		DefaultTableModel model = (DefaultTableModel) worker_table.getModel();
		model.setRowCount(0); // Clear existing rows

		List<Worker> workers = AdminController.getAllWorkers();
		for (Worker worker : workers) {
			model.addRow(new Object[]{
				worker.getWorkerId(),
				worker.getFirstName(),
				worker.getLastName(),
				worker.getEmail(),
				worker.getCategory(),
				worker.getPhone(),
				worker.getGender()
			});
		}
	}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button clear_btn;
    private swing.Button delete_btn;
    private swing.Button email_btn;
    private swing.TextField email_input;
    private swing.Button filter_btn;
    private swing.Button id_btn;
    private swing.TextField id_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Button phone_btn;
    private swing.TextField phone_input;
    private javax.swing.JTextField worker_id;
    private javax.swing.JTable worker_table;
    // End of variables declaration//GEN-END:variables
}
