/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mvc.View;

import controller.AuthenticationController;
import controller.UserController;
import java.awt.Color;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.WorkRequest;
import swing.RoundedBorder;

/**
 *
 * @author Legion
 */
public class UserNotification extends javax.swing.JPanel {

    /**
     * Creates new form UserNotification
     */
    public UserNotification() {
        initComponents();
		setOpaque(true);
		notification_panel.setOpaque(true);
		notification_panel.setLayout(new BoxLayout(notification_panel, BoxLayout.Y_AXIS));
		loadRequests();
    }


	public void loadRequests() {
		notification_panel.removeAll();

		List<WorkRequest> requests = UserController.getApprovedRequests(AuthenticationController.getCurrentUserId());
		System.out.println("requests: " +requests);

		if (requests != null) {  // Check for null since your getPendingRequests can return null
			for (WorkRequest request : requests) {
				// Create panel for each request
				JPanel requestPanel = new JPanel();
				requestPanel.setLayout(new BoxLayout(requestPanel, BoxLayout.X_AXIS));

				// Request label
				JLabel label = new JLabel("approved task  - worker ID: " + request.getWorkRequestId());
				requestPanel.add(label);
				requestPanel.add(Box.createHorizontalGlue());



				notification_panel.add(requestPanel);
				notification_panel.add(Box.createVerticalStrut(10));
			}
		}


		notification_panel.revalidate();
		notification_panel.repaint();
	}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notification_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        notification_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(126, 170, 236));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Worker Accepted Your Request");
        jLabel1.setBorder(new RoundedBorder(10, Color.WHITE,1));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(126, 170, 236));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Worker Accepted Your Request");
        jLabel2.setBorder(new RoundedBorder(10, Color.WHITE,1));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(126, 170, 236));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Worker Accepted Your Request");
        jLabel3.setBorder(new RoundedBorder(10, Color.WHITE,1));
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(126, 170, 236));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Worker Accepted Your Request");
        jLabel4.setBorder(new RoundedBorder(10, Color.WHITE,1));
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout notification_panelLayout = new javax.swing.GroupLayout(notification_panel);
        notification_panel.setLayout(notification_panelLayout);
        notification_panelLayout.setHorizontalGroup(
            notification_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notification_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(notification_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        notification_panelLayout.setVerticalGroup(
            notification_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notification_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(notification_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(notification_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel notification_panel;
    // End of variables declaration//GEN-END:variables
}
