/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mvc.View;

import controller.WorkerController;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.WorkRequest;

/**
 *
 * @author Legion
 */
public class WorkerNotification extends javax.swing.JPanel {

    /**
     * Creates new form WorkerNotification
     */
    public WorkerNotification() {
        initComponents();
		setOpaque(true);
		notification_panel.setOpaque(true);
		notification_panel.setLayout(new BoxLayout(notification_panel, BoxLayout.Y_AXIS));
		loadRequests();
    }

	public void loadRequests() {
		notification_panel.removeAll();

		List<WorkRequest> requests = WorkerController.getPendingRequests();

		if (requests != null) {  // Check for null since your getPendingRequests can return null
			for (WorkRequest request : requests) {
				// Create panel for each request
				JPanel requestPanel = new JPanel();
				requestPanel.setLayout(new BoxLayout(requestPanel, BoxLayout.X_AXIS));

				// Request label
				JLabel label = new JLabel("Accept User Request? - User ID: " + request.getUserId());
				requestPanel.add(label);
				requestPanel.add(Box.createHorizontalGlue());

				// Approve button
				swing.Button approveBtn = new swing.Button();
				approveBtn.setText("✓");
				approveBtn.setBackground(new java.awt.Color(0, 204, 0));
				approveBtn.setForeground(java.awt.Color.WHITE);
				approveBtn.addActionListener(e -> handleApprove(request.getWorkRequestId()));

				// Decline button
				swing.Button declineBtn = new swing.Button();
				declineBtn.setText("−");
				declineBtn.setBackground(new java.awt.Color(255, 51, 51));
				declineBtn.setForeground(java.awt.Color.WHITE);
				declineBtn.addActionListener(e -> handleDecline(request.getWorkRequestId()));

				requestPanel.add(approveBtn);
				requestPanel.add(Box.createHorizontalStrut(10));
				requestPanel.add(declineBtn);

				notification_panel.add(requestPanel);
				notification_panel.add(Box.createVerticalStrut(10));
			}
		}


		notification_panel.revalidate();
		notification_panel.repaint();
	}

	private void handleApprove(int requestId) {
		if (WorkerController.approveRequest(requestId)) {
			JOptionPane.showMessageDialog(this, "Request approved successfully!");
			loadRequests(); // Refresh the panel
		} else {
			JOptionPane.showMessageDialog(this, "Failed to approve request.",
					"Error", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void handleDecline(int requestId) {
		if (WorkerController.declineRequest(requestId)) {
			JOptionPane.showMessageDialog(this, "Request declined successfully!");
			loadRequests(); // Refresh the panel
		} else {
			JOptionPane.showMessageDialog(this, "Failed to decline request.",
					"Error", JOptionPane.ERROR_MESSAGE);
		}
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notification_panel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        notification_panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout notification_panelLayout = new javax.swing.GroupLayout(notification_panel);
        notification_panel.setLayout(notification_panelLayout);
        notification_panelLayout.setHorizontalGroup(
            notification_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        notification_panelLayout.setVerticalGroup(
            notification_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(notification_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(notification_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel notification_panel;
    // End of variables declaration//GEN-END:variables
}
