/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc.View;

import com.formdev.flatlaf.FlatIntelliJLaf;
import controller.AuthenticationController;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import model.LoginResult;
import swing.RippleEffectLabel;
import swing.RoundedBorder;

/**
 *
 * @author Legion
 */
public class WorkerLogin extends javax.swing.JFrame {
    private Point initialClick;

    /**
     * Creates new form worker
     */
    public WorkerLogin() {
        initComponents();
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        btnSignup.setVisible(false);
        makeDraggable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        panelBorder1 = new swing.PanelBorder();
        slidehover = new swing.PanelSlide();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblWorkerLogin = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        email_input = new swing.TextField();
        lblPassword = new javax.swing.JLabel();
        btnSignIn = new swing.Button();
        lblForgotPassword = new javax.swing.JLabel();
        lblClickHere = new javax.swing.JLabel();
        password_input = new swing.PasswordField();
        btnDashBoard = new swing.Button();
        titleBar = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        panelGradiente1.setColorPrimario(new java.awt.Color(204, 204, 0));
        panelGradiente1.setColorSecundario(new java.awt.Color(153, 153, 0));
        panelGradiente1.setMinimumSize(new java.awt.Dimension(900, 500));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        slidehover.setBackground(new java.awt.Color(255, 255, 255));
        slidehover.setOpaque(false);
        slidehover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slidehoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slidehoverMouseExited(evt);
            }
        });
        slidehover.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Here?");
        slidehover.add(jLabel1);
        jLabel1.setBounds(160, 120, 200, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create your account for free to access our services");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        slidehover.add(jLabel2);
        jLabel2.setBounds(50, 210, 470, 27);

        btnSignup = new RippleEffectLabel("Sign Up");
        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 20)); // You can adjust the font as needed
        btnSignup.setForeground(new java.awt.Color(255, 255, 255)); // Text color
        btnSignup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSignup.setBorder(new RoundedBorder(40, Color.WHITE, 2)); // Rounded border as in your original code
        btnSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        slidehover.add(btnSignup);
        btnSignup.setBounds(150, 350, 160, 60);

        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignupMouseEntered(evt);
            }

        });
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignupMouseClicked(evt);
            }
        });
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/workerlogin.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        slidehover.add(jLabel3);
        jLabel3.setBounds(0, 0, 530, 580);

        panelBorder1.add(slidehover);
        slidehover.setBounds(10, 10, 530, 580);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblWorkerLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblWorkerLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWorkerLogin.setForeground(new java.awt.Color(54, 66, 81));
        lblWorkerLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWorkerLogin.setText("Worker Login");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setText("Email :");

        email_input.setBackground(new java.awt.Color(250, 235, 204));
        email_input.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email_input.setPlaceholder("example@gmail.com");
        email_input.setRound(50);
        email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_inputActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setText("Password :");

        btnSignIn.setBackground(new java.awt.Color(35, 39, 153));
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setText("Sign In");
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSignIn.setRound(40);
        btnSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignInMouseClicked(evt);
            }
        });
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        lblForgotPassword.setText("Forgot Password?");

        lblClickHere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblClickHere.setForeground(new java.awt.Color(39, 35, 153));
        lblClickHere.setText("Click Here");
        lblClickHere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClickHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClickHereMouseClicked(evt);
            }
        });

        password_input.setBackground(new java.awt.Color(250, 235, 204));
        password_input.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnDashBoard.setBackground(new java.awt.Color(123, 26, 7));
        btnDashBoard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashBoard.setText("Home Page");
        btnDashBoard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDashBoard.setRound(40);
        btnDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashBoardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblEmail)
                                    .addGap(377, 377, 377))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblPassword)
                                    .addGap(346, 346, 346))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblWorkerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblForgotPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClickHere)
                        .addGap(17, 17, 17))
                    .addComponent(btnDashBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWorkerLogin)
                .addGap(22, 22, 22)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForgotPassword)
                    .addComponent(lblClickHere))
                .addGap(52, 52, 52)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        panelBorder1.add(jPanel2);
        jPanel2.setBounds(540, 10, 490, 570);

        titleBar.setBackground(new java.awt.Color(204, 204, 0));

        btnClose.setBackground(new java.awt.Color(204, 204, 0));
        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("x");
        btnClose.setOpaque(true);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(204, 204, 0));
        btnMinimize.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("-");
        btnMinimize.setOpaque(true);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 204, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login.png"))); // NOI18N
        jLabel4.setText("Worker Login");

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGradiente1.setLayer(panelBorder1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelGradiente1.setLayer(titleBar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelGradiente1Layout = new javax.swing.GroupLayout(panelGradiente1);
        panelGradiente1.setLayout(panelGradiente1Layout);
        panelGradiente1Layout.setHorizontalGroup(
            panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradiente1Layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGradiente1Layout.setVerticalGroup(
            panelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradiente1Layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void makeDraggable() {
        // MouseListener for dragging the window
        titleBar.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                initialClick = e.getPoint();  // Store initial click position
            }
        });
     
     titleBar.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                // Get the location of the window
                int x = getLocation().x;
                int y = getLocation().y;
                
                // Calculate how far the mouse has moved and set the new position
                int deltaX = e.getX() - initialClick.x;
                int deltaY = e.getY() - initialClick.y;
                
                setLocation(x + deltaX, y + deltaY);
            }
        });
    }
    private void slidehoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slidehoverMouseExited

    }//GEN-LAST:event_slidehoverMouseExited

    private void slidehoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slidehoverMouseEntered

    }//GEN-LAST:event_slidehoverMouseEntered

    private void lblClickHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClickHereMouseClicked
        // TODO add your handling code here:
        // Hide the current window and open Security
        Security securityWindow = new Security(this); // Pass the current instance
        securityWindow.setVisible(true);
        this.setVisible(false); // Hide the current window
    }//GEN-LAST:event_lblClickHereMouseClicked

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignInActionPerformed

    private void email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_inputActionPerformed

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/workerlogin.png")));
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        btnSignup.setVisible(false);

    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/workerloginblur.png")));
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        btnSignup.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void btnDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashBoardActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomePage home = new HomePage();
        home.setVisible(true);     
    }//GEN-LAST:event_btnDashBoardActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        // TODO add your handling code here:
        btnClose.setBackground(new Color(139, 0, 0));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        // TODO add your handling code here:
        btnClose.setBackground(new Color(204, 204, 0));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        // TODO add your handling code here:
        setState(AdminLogin.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        // TODO add your handling code here:
        btnMinimize.setBackground(new Color(211,211,211));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        // TODO add your handling code here:
        btnMinimize.setBackground(new Color(204, 204, 0));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignInMouseClicked
        // TODO add your handling code here:
		String email = email_input.getText().trim();
		String password = new String(password_input.getPassword());

		// Validate empty fields
		if (email.isEmpty() || password.isEmpty()) {
			JOptionPane.showMessageDialog(this,
					"Please fill in all fields!",
					"Error",
					JOptionPane.ERROR_MESSAGE);
			return;
		}


		// Attempt login
		LoginResult result = AuthenticationController.loginWorker(email, password);

		if (result.isSuccess()) {
			JOptionPane.showMessageDialog(this,
					"Welcome back, " + result.getName() + "!",
					"Login Successful",
					JOptionPane.INFORMATION_MESSAGE);
			new WorkerDashboard().setVisible(true);

			this.dispose();
		} else {
			// Login failed
			JOptionPane.showMessageDialog(this,
					"Invalid email or password!",
					"Login Failed",
					JOptionPane.ERROR_MESSAGE);

			// Clear password field but keep email
			password_input.setText("");
			password_input.requestFocus();
		}

    }//GEN-LAST:event_btnSignInMouseClicked
private void btnSignupMouseEntered(java.awt.event.MouseEvent evt) {    
  jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/workerloginblur.png")));
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        btnSignup.setVisible(true);
}
    private void btnSignupMouseClicked(java.awt.event.MouseEvent evt) {  
        WorkerSignup signup = new WorkerSignup();
        signup.setVisible(true);
        this.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatIntelliJLaf.setup();
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private swing.Button btnDashBoard;
    private javax.swing.JLabel btnMinimize;
    private swing.Button btnSignIn;
    private swing.TextField email_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClickHere;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblWorkerLogin;
    private swing.PanelBorder panelBorder1;
    private swing.PanelGradiente panelGradiente1;
    private swing.PasswordField password_input;
    private swing.PanelSlide slidehover;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables

private javax.swing.JLabel btnSignup;
}
