/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mvc.View;

import controller.WorkerController;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.WorkRequest;

/**
 *
 * @author Legion
 */
public class WorkerHistory extends javax.swing.JPanel {

    /**
     * Creates new form WorkerHistory
     */
    public WorkerHistory() {
        initComponents();
		setOpaque(true);
		history_panel.setOpaque(true);
		history_panel.setLayout(new BoxLayout(history_panel, BoxLayout.Y_AXIS));
loadRequests();
    }

	public void loadRequests() {
		history_panel.removeAll();

		List<WorkRequest> requests = WorkerController.getApprovedRequest();

		if (requests != null) {  // Check for null since your getPendingRequests can return null
			for (WorkRequest request : requests) {
				// Create panel for each request
				JPanel requestPanel = new JPanel();
				requestPanel.setLayout(new BoxLayout(requestPanel, BoxLayout.X_AXIS));

				// Request label
				JLabel label = new JLabel("Accepted User Request - User ID: " + request.getUserId());
				requestPanel.add(label);
				requestPanel.add(Box.createHorizontalGlue());


				history_panel.add(requestPanel);
				history_panel.add(Box.createVerticalStrut(10));
			}
		}


		history_panel.revalidate();
		history_panel.repaint();
	}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        history_panel = new javax.swing.JPanel();

        history_panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout history_panelLayout = new javax.swing.GroupLayout(history_panel);
        history_panel.setLayout(history_panelLayout);
        history_panelLayout.setHorizontalGroup(
            history_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        history_panelLayout.setVerticalGroup(
            history_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(history_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(history_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel history_panel;
    // End of variables declaration//GEN-END:variables
}
